import { run as audio } from "./audio.test";
import { run as beds } from "./beds.test";
import { run as blocks } from "./blocks.test";
import { run as chests } from "./chests.test";
import { run as crafting } from "./crafting.test";
import { run as craftscreen } from "./craftscreen.test";
import { run as daynight } from "./daynight.test";
import { run as debugspawn } from "./debugspawn.test";
import { run as debugtext } from "./debugtext.test";
import { run as dimensions } from "./dimensions.test";
import { run as drops } from "./drops.test";
import { run as fortress } from "./fortress.test";
import { summary } from "./harness";
import { run as inventory } from "./inventory.test";
import { run as lighting } from "./lighting.test";
import { run as liquids } from "./liquids.test";
import { run as portals } from "./portals.test";
import { run as portaltravel } from "./portaltravel.test";
import { run as projectiles } from "./projectiles.test";
import { run as structures } from "./structures.test";
import { run as mesher } from "./mesher.test";
import { run as nethergen } from "./nethergen.test";
import { run as mining } from "./mining.test";
import { run as mobs } from "./mobs.test";
import { run as physics } from "./physics.test";
import { run as placing } from "./placing.test";
import { run as progression } from "./progression.test";
import { run as session } from "./session.test";
import { run as sfx } from "./sfx.test";
import { run as smelting } from "./smelting.test";
import { run as storage } from "./storage.test";
import { run as ui } from "./ui.test";
import { run as vitals } from "./vitals.test";
import { run as world } from "./world.test";
import { run as worldgen } from "./worldgen.test";

worldgen();
nethergen();
fortress();
mesher();
blocks();
liquids();
portals();
portaltravel();
structures();
world();
physics();
placing();
lighting();
daynight();
mining();
inventory();
crafting();
craftscreen();
vitals();
mobs();
drops();
projectiles();
smelting();
chests();
beds();
storage();
session();
dimensions();
progression();
sfx();
debugtext();
debugspawn();
ui();
// **音だけは非同期。** `OfflineAudioContext` の書き出しを待つ必要があるので、
// ここで await する（`summary()` より前に終わらせること）。
await audio();
summary();
