import { run as crafting } from "./crafting.test";
import { run as daynight } from "./daynight.test";
import { summary } from "./harness";
import { run as inventory } from "./inventory.test";
import { run as lighting } from "./lighting.test";
import { run as mesher } from "./mesher.test";
import { run as mining } from "./mining.test";
import { run as vitals } from "./vitals.test";
import { run as world } from "./world.test";
import { run as worldgen } from "./worldgen.test";

worldgen();
mesher();
world();
lighting();
daynight();
mining();
inventory();
crafting();
vitals();
summary();
